### ISSUE TITLE
Custom compile command

### ISSUE THREAD

**Issue by bkiefer** [yoshegg/rudibugger#10]
Should be possible to type in the compile command to execute in the terminal into a text field,
e.g., if compilation is done in a mvn install step.

**Comment by bkiefer** [comment]
That could be something that you set in the dipalCompile.yml. So you maybe do not need another GUI element for that.

**Comment by yoshegg** [comment]
This is now possible. An additional entry for a map in `diaplCompile.yml` is required. E.g.

```
customCompileCommands:
  "Compile without maven": "asdf"
```

When loading the project, the compile button will be replaced automatically.
