### ISSUE TITLE
get either a button or an initial splash dialog for "open last project"

### ISSUE THREAD

**Issue by bkiefer** [yoshegg/rudibugger#13]

**Comment by yoshegg** [comment]
rudibugger now opens the last opened project from the previous session (if the project has not been closed) when started. 
(N.B.: After pulling this update, you will see the effect **after the second time starting rudibugger**.)

As this is the normal behaviour in IDEs as NetBeans, I don't think a button or splash dialog will be needed. Feel free to reopen issue if you don't agree.
