### ISSUE TITLE
Super Power Signal lamp.

### ISSUE THREAD

**Issue by bkiefer** [yoshegg/rudibugger#17]
Extend the signal lamp to provide the following functionality: 
- green: compiled and no error/warning
- yellow: compiled, only warnings, right click gives you a menu of warnings to jump to
- orange: compile, with errors (and possibly warnings), right click gives you a menu of errs/warnings to jump to
- red: compile, with fatal error, right click ....
- pink: recompile necessary, left click compiles, right click ...
- hover explains the status

**Comment by yoshegg** [comment]
- Green: done
- Yellow: done
- Orange: done
- Red: not yet, must change things in VOnDA first, but there's another issue for that. 
- Pink: in other icon, left click not necessary. If you have multiple compile commands, one should be able to distinguish, but the default button is just a few pixels away.
- hover: works
