### ISSUE TITLE
Parse failures are out of the scope of "click and go to error"

### ISSUE THREAD

**Issue by bkiefer** [yoshegg/rudibugger#18]
If a parse failure occurs, there is no new info file. Nevertheless, it would be nice to have the same functionality as for the type errors (even more so).

**Comment by yoshegg** [comment]
Almost done, additions to VOnDA have been amde

**Comment by yoshegg** [comment]
Done in commit eda70bb703b08b90c209a14f4d92b2155021daa9 .
