### ISSUE TITLE
Reconnect button to runtime system with connection status (color?) 

### ISSUE THREAD

**Issue by bkiefer** [yoshegg/rudibugger#19]
Should enable reconnecting to the server in case of disconnect.

**Comment by yoshegg** [comment]
Could you elaborate on that? Or is this already done?

**Comment by bkiefer** [comment]
There is a reconnect button. Sometimes i'm not sure if it works, but that could be due to the underlying code. Must be tested.

**Comment by yoshegg** [comment]
Has to do with issue #23
