### ISSUE TITLE
Emacs: Start compilation

### ISSUE THREAD

**Issue by yoshegg** [yoshegg/rudibugger#30]

**Comment by yoshegg** [comment]
Provide lisp function called `compile` (Inspiration: `j2e-send`), also look at `j2e-after-save`

**Comment by yoshegg** [comment]
Should be done, requesting feedback. If okay, please close.

**Comment by bkiefer** [comment]
Works almost, but the `_model.project.getDefaultCompileCommand()` returns an empty string when called from the emacs support code.

**Comment by yoshegg** [comment]
How can I reproduce this behaviour in emacs?

**Comment by bkiefer** [comment]
Change a file and save it.

**Comment by bkiefer** [comment]
Fixed by 62a46dd4d16074c3a816f320d8f84c022d4f7b78
