### ISSUE TITLE
Click on error and jump to line

### ISSUE THREAD

**Issue by yoshegg** [yoshegg/rudibugger#8]

**Comment by yoshegg** [comment]
can now be done by right clicking on an erroneous import (also shown with a red background) and choosing to open concerned file and jumping to error.

**Comment by bkiefer** [comment]
It seems WARNings are left out, is that intentional?

**Comment by yoshegg** [comment]
From now on warnings are also included.

**Comment by bkiefer** [comment]
Where do i see the list of errors/warnings i can click on?

**Comment by yoshegg** [comment]
in the context menu of the respective import
